export const employees = [
    {
      id: 1,
      name: 'John Doe',
      designation: 'Software Engineer',
      age: 30,
      department: 'IT',
      gender: 'Male',
      salary: 75000,
      experience: 5,
      email: 'john.doe@example.com',
      phone: '123-456-7890',
      address: '123 Main St, New York, NY'
    },
    {
      id: 2,
      name: 'Jane Smith',
      designation: 'Project Manager',
      age: 35,
      department: 'Management',
      gender: 'Female',
      salary: 90000,
      experience: 10,
      email: 'jane.smith@example.com',
      phone: '987-654-3210',
      address: '456 Oak St, San Francisco, CA'
    },
    {
      id: 3,
      name: 'Robert Brown',
      designation: 'HR Manager',
      age: 40,
      department: 'Human Resources',
      gender: 'Male',
      salary: 85000,
      experience: 12,
      email: 'robert.brown@example.com',
      phone: '456-789-0123',
      address: '789 Pine St, Los Angeles, CA'
    },
    {
      id: 4,
      name: 'Emily Johnson',
      designation: 'UX Designer',
      age: 28,
      department: 'Design',
      gender: 'Female',
      salary: 70000,
      experience: 4,
      email: 'emily.johnson@example.com',
      phone: '654-321-0987',
      address: '101 Maple Ave, Austin, TX'
    },
    {
      id: 5,
      name: 'Michael Williams',
      designation: 'DevOps Engineer',
      age: 32,
      department: 'IT',
      gender: 'Male',
      salary: 80000,
      experience: 6,
      email: 'michael.williams@example.com',
      phone: '321-654-9870',
      address: '202 Cedar Rd, Seattle, WA'
    },
    {
      id: 6,
      name: 'Sophia Martinez',
      designation: 'Marketing Manager',
      age: 37,
      department: 'Marketing',
      gender: 'Female',
      salary: 88000,
      experience: 9,
      email: 'sophia.martinez@example.com',
      phone: '741-852-9630',
      address: '303 Elm St, Chicago, IL'
    },
    {
      id: 7,
      name: 'William Anderson',
      designation: 'Business Analyst',
      age: 34,
      department: 'Business',
      gender: 'Male',
      salary: 77000,
      experience: 8,
      email: 'william.anderson@example.com',
      phone: '369-258-1470',
      address: '404 Birch St, Denver, CO'
    },
    {
      id: 8,
      name: 'Olivia Thomas',
      designation: 'Product Manager',
      age: 29,
      department: 'Product',
      gender: 'Female',
      salary: 95000,
      experience: 7,
      email: 'olivia.thomas@example.com',
      phone: '159-357-4860',
      address: '505 Aspen St, Boston, MA'
    },
    {
      id: 9,
      name: 'James White',
      designation: 'System Administrator',
      age: 42,
      department: 'IT',
      gender: 'Male',
      salary: 78000,
      experience: 15,
      email: 'james.white@example.com',
      phone: '951-753-8640',
      address: '606 Redwood St, Houston, TX'
    },
    {
      id: 10,
      name: 'Emma Green',
      designation: 'Data Scientist',
      age: 31,
      department: 'Data Analytics',
      gender: 'Female',
      salary: 98000,
      experience: 6,
      email: 'emma.green@example.com',
      phone: '753-951-2580',
      address: '707 Willow St, Miami, FL'
    }
  ];